In [24]:
%matplotlib inline 
import pandas as pd            
import numpy as np              
import matplotlib.pyplot as plt
import tensorflow as tf        
dataframe = pd.read_csv("data.csv") 
dataframe = dataframe.drop(["index", "area", "sq_price"], axis=1) 
dataframe = dataframe[0:10]
dataframe

bathrooms     price
0        3.0  399900.0
1        3.0  329900.0
2        3.0  369000.0
3        2.0  232000.0
4        4.0  539900.0
5        4.0  299900.0
6        3.0  314900.0
7        3.0  198999.0
8        3.0  212000.0
9        3.0  242500.0

In [25]:
dataframe.loc[:, ("y1")] = [1, 0, 0, 0, 0, 0, 0, 0, 0, 1] 
                                                          
dataframe.loc[:, ("y2")] = dataframe["y1"] == 0           
dataframe.loc[:, ("y2")] = dataframe["y2"].astype(int)    
dataframe 


bathrooms     price  y1  y2
0        3.0  399900.0   1   0
1        3.0  329900.0   0   1
2        3.0  369000.0   0   1
3        2.0  232000.0   0   1
4        4.0  539900.0   0   1
5        4.0  299900.0   0   1
6        3.0  314900.0   0   1
7        3.0  198999.0   0   1
8        3.0  212000.0   0   1
9        3.0  242500.0   1   0

In [26]:
inputX = dataframe.loc[:, ['bathrooms', 'price']].as_matrix()
inputY = dataframe.loc[:, ["y1", "y2"]].as_matrix()

In [27]:
inputX

array([[  3.00000000e+00,   3.99900000e+05],
       [  3.00000000e+00,   3.29900000e+05],
       [  3.00000000e+00,   3.69000000e+05],
       [  2.00000000e+00,   2.32000000e+05],
       [  4.00000000e+00,   5.39900000e+05],
       [  4.00000000e+00,   2.99900000e+05],
       [  3.00000000e+00,   3.14900000e+05],
       [  3.00000000e+00,   1.98999000e+05],
       [  3.00000000e+00,   2.12000000e+05],
       [  3.00000000e+00,   2.42500000e+05]])

In [28]:
inputY

array([[1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0]])

In [29]:
learning_rate = 0.000001
training_epochs = 2000
display_step = 50
n_samples = inputY.size

In [30]:
x = tf.placeholder(tf.float32, [None, 2])   
            
W = tf.Variable(tf.zeros([2, 2]))           
    
b = tf.Variable(tf.zeros([2]))              

y_values = tf.add(tf.matmul(x, W), b)       
    
y = tf.nn.sigmoid(y_values)                 
    
y_ = tf.placeholder(tf.float32, [None,2])

In [31]:
cost = tf.reduce_sum(tf.pow(y_ - y, 2))/(2*n_samples)
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)
for i in range(training_epochs):  
    sess.run(optimizer, feed_dict={x: inputX, y_: inputY}) 

    if (i) % display_step == 0:
        cc = sess.run(cost, feed_dict={x: inputX, y_:inputY})
        print "Training step:", '%04d' % (i), "cost=", "{:.9f}".format(cc)
print "Optimization Finished!"
training_cost = sess.run(cost, feed_dict={x: inputX, y_: inputY})
print "Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n'

Instructions for updating:
Use `tf.global_variables_initializer` instead.
Training step: 0000 cost= 0.100000001
Training step: 0050 cost= 0.100000001
Training step: 0100 cost= 0.100000001
Training step: 0150 cost= 0.100000001
Training step: 0200 cost= 0.100000001
Training step: 0250 cost= 0.100000001
Training step: 0300 cost= 0.100000001
Training step: 0350 cost= 0.100000001
Training step: 0400 cost= 0.100000001
Training step: 0450 cost= 0.100000001
Training step: 0500 cost= 0.100000001
Training step: 0550 cost= 0.100000001
Training step: 0600 cost= 0.100000001
Training step: 0650 cost= 0.100000001
Training step: 0700 cost= 0.100000001
Training step: 0750 cost= 0.100000001
Training step: 0800 cost= 0.100000001
Training step: 0850 cost= 0.100000001
Training step: 0900 cost= 0.100000001
Training step: 0950 cost= 0.100000001
Training step: 1000 cost= 0.100000001
Training step: 1050 cost= 0.100000001
Training step: 1100 cost= 0.100000001
Training step: 1150 cost= 0.100000001
Training step:

In [32]:
sess.run(y, feed_dict={x: inputX })

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.]], dtype=float32)

In [33]:
sess.run(tf.nn.sigmoid([1., 2.]))

array([ 0.7310586 ,  0.88079703], dtype=float32)